In [0]:
!pip3 install deeppavlov

In [0]:
!python -m deeppavlov install intents_snips

In [0]:
#pip install keras-bert

In [0]:
#!pip3 install deeppavlov
!python -m deeppavlov install tfidf_vectorizer
#!python -m deeppavlov download tfidf_vectorizer
#!python -m deeppavlov interact tfidf_vectorizer
#!pip install email-validator
#!python -m deeppavlov train paraphraser_rubert

In [0]:
#%tensorflow_version 2.x
import tensorflow as tf
import deeppavlov as dp
from bert_dp.modeling import BertConfig, BertModel
from bert_dp.optimization import AdamWeightDecayOptimizer
from bert_dp.preprocessing import InputFeatures
from deeppavlov import build_model, configs
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from tensorflow import keras
from deeppavlov.models.bert.bert_classifier import BertClassifierModel
from tensorflow.keras import layers
from keras.models import Sequential
from keras.models import Model
from keras.layers import Input, Dense


In [0]:
model = build_model(configs.vectorizer.tfidf_vectorizer, download=True)

2020-02-02 09:13:55.655 INFO in 'deeppavlov.core.data.utils'['utils'] at line 80: Downloading from http://files.deeppavlov.ai/datasets/wikitext_ru.zip to /root/.deeppavlov/downloads/wikitext_ru.zip
100%|██████████| 146/146 [00:00<00:00, 335kB/s]
2020-02-02 09:13:55.661 INFO in 'deeppavlov.core.data.utils'['utils'] at line 237: Extracting /root/.deeppavlov/downloads/wikitext_ru.zip archive into /root/.deeppavlov/downloads/wiki


BadZipFile: ignored

In [0]:
model = BertClassifierModel(configs.classifiers.paraphraser_rubert,2,None,False,False,return_probas = True,
                            hidden_keep_prob=None, optimizer=None, num_warmup_steps=None, 
                            weight_decay_rate=0.01, pretrained_bert=, min_learning_rate=1e-06)

In [0]:
#нам нужно написать функции токенайзера для входного набора данных
#затем мы токенизированные слова даем на вход руБерт, где он с учетом bpe превращает в векторное представление текст
#нейронная сеть для классификации при условии, где параметр а лежит в отрезке [0,1]

In [0]:
def tokenize(train_text):
  tokens = word_tokenize(train_text)
  return tokens

In [0]:
text1 = 'Эта кошка была замечательная'
text12 = ' Эта животное была замечательная'
text2 = 'Эта кошка была замечательная'
text22 = 'Эта кирпич была замечательная'
text = np.array([[text1,1],[text2,0]])
print(text)

[['Эта кошка была замечательная' '1']
 ['Эта кошка была замечательная' '0']]


In [0]:
b = []
for line in text:
  tokens = tokenize(line[0])
  b.append((tokens,line[1]))

text_a = str(tokenize(text1))
text_a1 = str(tokenize(text12))
text_b = str(tokenize(text2))
text_b1 = str(tokenize(text22))
print(text_a,text_b)

['Эта', 'кошка', 'была', 'замечательная'] ['Эта', 'кошка', 'была', 'замечательная']


In [0]:
model([text_a,text_a1],[text_b,text_b1])

array([1, 1])

In [0]:
from deeppavlov.core.data.utils import download

download("./stanfordSentimentTreebank.zip", source_url="http://files.deeppavlov.ai/datasets/stanfordSentimentTreebank.zip")

In [0]:
!unzip stanfordSentimentTreebank.zip

In [0]:
!ls stanfordSentimentTreebank/

In [0]:
from deeppavlov.dataset_readers.basic_classification_reader import BasicClassificationDatasetReader

In [0]:
reader = BasicClassificationDatasetReader()
data = reader.read(data_path="./stanfordSentimentTreebank", 
                   train="train_binary.csv", valid="valid_binary.csv", test="test_binary.csv",
                   x="text", y="binary_label")

In [0]:
data.keys()

In [0]:
data["train"]

In [0]:
! python -m deeppavlov install bert_as_summarizer

In [0]:
model = build_model(configs.summarization.bert_as_summarizer, download=True)
# вызвать нужный метод у модели
model.pipe[-1][-1]._get_nsp_predictions(['Hey', 'Hey'], ['Hello', 'Goodbye'])

2020-02-02 11:33:33.563 INFO in 'deeppavlov.core.data.utils'['utils'] at line 80: Downloading from http://files.deeppavlov.ai/deeppavlov_data/bert/rubert_cased_L-12_H-768_A-12_v2.tar.gz to /root/.deeppavlov/downloads/rubert_cased_L-12_H-768_A-12_v2.tar.gz
100%|██████████| 662M/662M [03:02<00:00, 3.63MB/s]
2020-02-02 11:36:36.18 INFO in 'deeppavlov.core.data.utils'['utils'] at line 237: Extracting /root/.deeppavlov/downloads/rubert_cased_L-12_H-768_A-12_v2.tar.gz archive into /root/.deeppavlov/downloads/bert_models
2020-02-02 11:36:54.96 INFO in 'deeppavlov.models.bert.bert_as_summarizer'['bert_as_summarizer'] at line 102: [initializing model with Bert from /root/.deeppavlov/downloads/bert_models/rubert_cased_L-12_H-768_A-12_v2/bert_model.ckpt]


array([0.47669053, 0.4697402 ], dtype=float32)

In [0]:
text1 = 'Эта кошка была замечательная'
text12 = ' Я любила ее'
text2 = 'Эта кошка была замечательная'
text22 = 'Кукуха поехала уже от интенсива'

In [0]:
model.pipe[-1][-1]._get_nsp_predictions([text1, text1], [text12, text22])

array([0.49392563, 0.48028386], dtype=float32)

In [0]:
model = BertClassifierModel(configs.summarization.bert_as_summarizer,2,None,False,False,return_probas = True,
                            hidden_keep_prob=None, optimizer=text_a, num_warmup_steps=None, 
                            weight_decay_rate=0.01, pretrained_bert=True, min_learning_rate=0.00001)

In [0]:
from deeppavlov.models.preprocessors.str_lower import StrLower

ImportError: ignored

In [0]:
txt1 = 'Эта кошка самая замечательная. Эта животное самая замечательная.'
txt2 = 'Эта кошка самая замечательная. Эта кирпич самая замечательная'

In [0]:
from deeppavlov.dataset_iterators.basic_classification_iterator import BasicClassificationDatasetIterator

In [0]:
iterator = BasicClassificationDatasetIterator(, seed=42, shuffle=True)

NameError: ignored

In [0]:
from deeppavlov.models.tokenizers.nltk_tokenizer import NLTKTokenizer

In [0]:
tokenizer = NLTKTokenizer()

In [0]:
train_data = tokenizer([text1,text12,text2,text22])

In [0]:
from deeppavlov.core.data.utils import download

download("./glove.6B.100d.txt", source_url="http://files.deeppavlov.ai/embeddings/glove.6B.100d.txt")

2020-02-02 09:47:25.417 INFO in 'deeppavlov.core.data.utils'['utils'] at line 80: Downloading from http://files.deeppavlov.ai/embeddings/glove.6B.100d.txt to /content/glove.6B.100d.txt
347MB [00:47, 7.35MB/s]


In [0]:
from deeppavlov.models.embedders.glove_embedder import GloVeEmbedder

embedder = GloVeEmbedder(load_path="./glove.6B.100d.txt", 
                         pad_zero=True
                        )

2020-02-02 09:49:07.87 INFO in 'deeppavlov.models.embedders.glove_embedder'['glove_embedder'] at line 52: [loading GloVe embeddings from `/content/glove.6B.100d.txt`]
/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:402: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [0]:
embedder.dim

100

In [0]:
embedding_data = embedder(train_data)

In [0]:
embedder(train_data).shape

(4, 4, 100)

In [0]:
from deeppavlov.core.data.simple_vocab import SimpleVocabulary

In [0]:
vocab = SimpleVocabulary(save_path="./binary_classes.dict")

2020-02-02 10:07:08.455 WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 49: No load path is set for SimpleVocabulary in 'infer' mode. Using save path instead


In [0]:
a = iterator.get_instances(data_type="train")
a

NameError: ignored